CREATE TABLE Notes (
    Uid INT IDENTITY(1,1) PRIMARY KEY,
    UserUID INT NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    UpdatedDate DATETIME NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);