--create database MyAppDb;

CREATE TABLE Users (
    Uid INT IDENTITY(1,1) PRIMARY KEY,
    UUid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Role NVARCHAR(100) NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    LastLogin DATETIME NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
);
